#!/usr/bin/env ansible-playbook
---
- name: Start hcloud_instance
  hosts: all
  connection: local
  gather_facts: no
  serial: 1
  tasks:
    - debug:
        msg: "{{ inventory_hostname_short }}-priv.{{ base_domain }}. => {{ hetzner_ip }} "

    - name: Create private DNS record at GCP
      gcp_dns_resource_record_set:
        name: "{{ inventory_hostname_short }}-private.{{ base_domain }}."
        managed_zone:
          name: "{{ gcp_managed_zone_name }}"
          dnsName: "{{ gcp_managed_zone_domain }}"
        type: A
        ttl: 300
        target:
          - "{{ internal_ip }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_serviceaccount_file }}"
        state: present

    - name: Create public DNS record at GCP
      gcp_dns_resource_record_set:
        name: "{{ inventory_hostname }}."
        managed_zone:
          name: "{{ gcp_managed_zone_name }}"
          dnsName: "{{ gcp_managed_zone_domain }}"
        type: A
        ttl: 300
        target:
          - "{{ hetzner_ip }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_serviceaccount_file }}"
        state: present
