---
extends: default
rules:
  line-length: disable
  document-start: disable
  indentation:
    indent-sequences: whatever
  hyphens:
    max-spaces-after: 4
  truthy:
    allowed-values: ["true", "yes", "false", "no"]
    check-keys: true
