---
- name: Run once block
  run_once: true
  delegate_to: localhost
  block:
  - name: Ensure installion directory
    file:
      path: "{{ openshift_install_dir }}"
      state: directory

  - name: Create install config
    template:
      src: install-config.yaml.j2
      dest: "{{ openshift_install_dir }}/install-config.yaml"

  - name: Save install-config from deletion
    copy:
      dest: "{{ openshift_install_dir }}/install-config.yaml.original"
      src: "{{ openshift_install_dir }}/install-config.yaml"

  - name: Create ignition files
    command: "{{ openshift_install_command }} --dir={{ openshift_install_dir }} create ignition-configs"
    args:
      creates: "{{ openshift_install_dir}}/.openshift_install_state.json"


- name: Configure storage part
  set_fact:
    storage_json: |
      { "storage": {"files": [
        {
          "path": "/etc/hostname",
          "contents": {
            "source": "data:,{{ internal_hostname }}"
          },
          "mode": 420
        }
      ]}}

- name: Fetch master ignition
  set_fact:
    master_json: "{{ lookup('file',  openshift_install_dir ~ '/master.ign')}}"

- name: Create ignition
  copy:
    content: "{{ master_json | combine( storage_json ) }}"
    dest: /root/config.ignition
