---

- name: Run installer
  shell: |
    ./coreos-installer install {{ install_device }} \
      --ignition-file config.ignition \
      --copy-network --firstboot-args="rd.neednet=1" \
      --network-dir ./network-config/ \
      --insecure \
      --image-file rhcos-4.6.1-x86_64-metal.x86_64.raw.gz
  register: installer

- name: Output of installer
  debug:
    var: installer

- name: Reboot
  shell: reboot --reboot
  tags:
    reboot