---

- name: Create DNS record at GCP
  gcp_dns_resource_record_set:
    name: "api-int.{{ cluster_name }}.{{ base_domain }}."
    managed_zone:
      name: "{{ gcp_managed_zone_name }}"
      dnsName: "{{ gcp_managed_zone_domain }}"
    type: A
    ttl: 120
    target:
      - "{{ internal_ip }}"
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_serviceaccount_file }}"
    state: present


- name: Create DNS record at GCP
  gcp_dns_resource_record_set:
    name: "{{ item }}.{{ cluster_name }}.{{ base_domain }}."
    managed_zone:
      name: "{{ gcp_managed_zone_name }}"
      dnsName: "{{ gcp_managed_zone_domain }}"
    type: A
    ttl: 120
    target:
      - "{{ hetzner_ip }}"
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_serviceaccount_file }}"
    state: present
  with_items:
    - api
    - "*.apps"
