---
- name: Run once block
  run_once: true
  delegate_to: localhost
  block:
  - name: Ensure installion directory
    file:
      path: "{{ openshift_install_dir }}"
      state: directory

  - name: Create install config
    template:
      src: install-config.yaml.j2
      dest: "{{ openshift_install_dir }}/install-config.yaml"

  - name: Save install-config from deletion
    copy:
      dest: "{{ openshift_install_dir }}/install-config.yaml.original"
      src: "{{ openshift_install_dir }}/install-config.yaml"


  - name: Create manifests
    command: "{{ openshift_install_command }} --dir={{ openshift_install_dir }} create manifests"


  - name: Enable IPSec
    copy:
      dest: "{{ openshift_install_dir }}/manifests/cluster-network-03-config.yml"
      content: |
        apiVersion: operator.openshift.io/v1
        kind: Network
        metadata:
          name: cluster
        spec:
          defaultNetwork:
            ovnKubernetesConfig:
              ipsecConfig: {}

  - name: Create ignition files
    command: "{{ openshift_install_command }} --dir={{ openshift_install_dir }} create ignition-configs"
    args:
      creates: "{{ openshift_install_dir}}/bootstrap.ign"


- name: Fetch master ignition
  set_fact:
    source_ignition: "{{ lookup('file',  openshift_install_dir ~ '/' ~ ignition_name )}}"

- name: Build storage.files
  set_fact:
    files: "{{ source_ignition.storage.files | default([]) + [
        {
          'path': '/etc/hostname',
          'contents': {
            'source': 'data:,' ~ inventory_hostname
          },
          'mode': 420
        }
    ] }}"


- name: Build storage part
  set_fact:
    storage: "{ 'storage': {'files': {{files}} } }"

- name: Create ignition
  copy:
    content: "{{ source_ignition | combine( storage ) }}"
    dest: /root/config.ignition
