---
- include_tasks: boot-rescue.yaml
  when: ansible_hostname != 'rescue'

- name: Check download urls
  uri:
    method: HEAD
    url: "{{ item }}"
    status_code:
      - 200
      # Forbidden because of github forwards to aws s3.
      # HEAD request to S3 is forbidden
      - 403
  with_items:
    - "{{ coreos_install_url }}"
    - "{{ coreos_image_url }}"


- name: Download RCOS
  get_url:
    url: "{{ coreos_image_url }}"
    dest: "{{ coreos_image }}"

- name: Download coreos-installer
  get_url:
    url: "{{ coreos_install_url }}"
    dest: "/root/{{ coreos_install_url | basename }}"
    mode: a+x

- name: Create network config folder
  ansible.builtin.file:
    path: /root/network-config
    state: directory

- name: "Create Network {{ network_primary_interface }}.nmconnection"
  ansible.builtin.template:
    src: device.nmconnection
    dest: "/root/network-config/{{ network_primary_interface }}.nmconnection"
    owner: root
    group: root
    mode: '0600'

- name: "Create ssh-only.ignition"
  ansible.builtin.template:
    src: ssh-only.ignition
    dest: "/root/ssh-only.ignition"
    owner: root
    group: root
    mode: '0600'

- name: Info
  debug:
    msg:
      - "Please run:"
      - "./coreos-installer install {{ install_device }} --ignition-file ssh-only.ignition --copy-network --firstboot-args='rd.neednet=1' --network-dir ./network-config/ --insecure --image-file {{ coreos_image }}"
