---

- name: Run installer
  shell: |
    ./coreos-installer install {{ install_device }} \
      --ignition-file config.ignition \
      --copy-network --firstboot-args="rd.neednet=1" \
      --network-dir ./network-config/ \
      --insecure \
      --image-file {{ coreos_image }}
  register: installer

- name: Output of installer
  debug:
    var: installer

- name: Reboot
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  tags:
    reboot
