---
- include_tasks: boot-rescue.yaml
  when: ansible_hostname != 'rescue'

- name: Stop default hetzner sw raid setup
  shell: "mdadm --stop md0 md1 md2"

- name: Wipe disk one
  shell: "wipefs -a /dev/{{ hetzner_disk1 }}"

- name: Wipe disk two
  shell: "wipefs -a /dev/{{ hetzner_disk2 }}"
